# Generated by Django 6.0.6 on 2026-06-13 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='uploads/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('row_count_raw', models.IntegerField(blank=True, null=True)),
                ('row_count_clean', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spend_inr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_spend_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('top_merchants', models.JSONField(default=dict)),
                ('anomaly_count', models.IntegerField(default=0)),
                ('narrative', models.TextField(blank=True, default='')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('category_spend', models.JSONField(default=list)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='zserver.job')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('merchant', models.CharField(max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('account_id', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_reason', models.TextField(blank=True, default='')),
                ('llm_category', models.CharField(blank=True, max_length=50, null=True)),
                ('llm_failed', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='zserver.job')),
            ],
            options={
                'ordering': ['date', 'txn_id'],
            },
        ),
    ]
